### ISSUE TITLE
화상 동상 사진을 인식 후

### ISSUE THREAD

**Issue by leegangryong1** [younga13/mental-health-chatbot#11]
화상 동상 사진을 인식한 후 화상입니다 동상입니다 알려주는게 아니랑 건강 챗봇에 맞게 봐꿔야하지않을까요?

**Comment by younga13** [comment]
화상과 동상을 인식 후 그에 맞는 응급처치를 할 수 있게 응급처치를 알려주는 것으로 바꿨습니다.
